# Last Modified: Sat Apr 25 08:25:23 2020
#include <tunables/global>

/home/smar/.local/share/Steam/steam.sh {
  #include <abstractions/X>
  #include <abstractions/audio>
  #include <abstractions/base>
  #include <abstractions/bash>
  #include <abstractions/consoles>
  #include <abstractions/dbus-session-strict>
  #include <abstractions/gnome>
  #include <abstractions/nameservice>
  #include <abstractions/qt5>
  #include <abstractions/smar_kde>
  #include <abstractions/ssl_certs>
  #include <abstractions/user-tmp>
  #include <abstractions/vulkan>

  deny ptrace trace peer=unconfined,

  ptrace read peer=unconfined,
  ptrace trace peer=/home/smar/.local/share/Steam/steam.sh,

  deny /proc/*/stat r,

  / r,
  /bin/bash mrix,
  /dev/ r,
  /dev/bus/usb/ r,
  /dev/bus/usb/** rw,
  /dev/disk/by-id/ r,
  /dev/hidraw* rw,
  /dev/input/event* rw,
  /dev/ptmx rw,
  /etc/fish/conf.d/ r,
  /etc/fish/config.fish r,
  /etc/os-release r,
  /etc/shells r,
  /etc/udev/udev.conf r,
  /etc/xdg/accept-languages.codes r,
  /etc/xdg/menus/ r,
  /etc/xdg/menus/applications-merged/ r,
  /home/smar/.local/share/Steam/.steam_exec_test.sh Cx,
  /home/smar/.local/share/Steam/steamapps/common/*/* ux,
  /home/smar/.local/share/Steam/ubuntu12_32/gameoverlayui px,
  /home/smar/Tiedostot/Steam/steamapps/common/*/* ux,
  /lib/ld-2.26.so mrix,
  /lib64/ld-2.26.so mrix,
  /proc/ r,
  /proc/*/net/dev r,
  /proc/locks r,
  /proc/sys/kernel/osrelease r,
  /proc/version r,
  /run/udev/data/* r,
  /sbin/lspci mrix,
  /sys/ r,
  /sys/bus/ r,
  /sys/bus/pci/devices/ r,
  /sys/bus/usb/devices/ r,
  /sys/class/ r,
  /sys/class/*/ r,
  /sys/devices/ r,
  /sys/devices/system/** r,
  /usr/ r,
  /usr/bin/ r,
  /usr/bin/* mrix,
  /usr/local/ r,
  /usr/sbin/ r,
  /usr/share/fish/* r,
  /usr/share/fish/** r,
  /usr/share/fonts/** rk,
  /usr/share/kservices5/* r,
  /usr/share/zenity/* r,
  @{HOME}*/Steam/.steam_exec_test.sh mrix,
  @{HOME}/.local/share/Steam/linux32/steamerrorreporter mrix,
  @{HOME}/.local/share/Steam/steam.sh mrix,
  @{HOME}/.local/share/Steam/ubuntu12_32/gldriverquery mrix,
  @{HOME}/.local/share/Steam/ubuntu12_32/steam mrix,
  @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/* mrix,
  @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/i386/usr/bin/* mrix,
  @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh Px,
  @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/setup.sh Px,
  @{HOME}/.local/share/Steam/ubuntu12_64/gldriverquery mrix,
  @{HOME}/.local/share/Steam/ubuntu12_64/steamwebhelper.sh px,
  @{HOME}/.local/share/Steam/ubuntu12_64/vulkandriverquery mrix,
  owner /dev/shm/* rw,
  owner /dev/shm/u*-ValveIPCSharedObj-Steam rwk,
  owner /home/*/.cache/icon-cache.kcache rw,
  owner /home/*/.cache/ksycoca5_* r,
  owner /home/*/.cache/mesa_shader_cache/** k,
  owner /home/*/.cache/radv_builtin_shaders64 r,
  owner /home/*/.config/kdeglobals r,
  owner /home/*/.config/menus/ r,
  owner /home/*/.config/menus/applications-merged/ r,
  owner /home/*/.local/share/RecentDocuments/ r,
  owner /home/*/.local/share/RecentDocuments/* w,
  owner /home/*/.local/share/RecentDocuments/*.T11340 r,
  owner /home/*/.local/share/RecentDocuments/.* k,
  owner /home/*/.local/share/RecentDocuments/.* r,
  owner /home/*/.local/share/RecentDocuments/watch.desktop.* r,
  owner /home/*/.local/share/RecentDocuments/watch.desktop.lock wk,
  owner /home/*/.local/share/Steam/WINDOWSTEMPDIR_FONTCONFIG_CACHE/* l,
  owner /home/*/.steam/registry.vdf k,
  owner /proc/*/cmdline r,
  owner /proc/*/environ r,
  owner /proc/*/fd/ r,
  owner /proc/*/fdinfo/* r,
  owner /proc/*/mem r,
  owner /proc/*/task/ r,
  owner /run/user/1000/* rw,
  owner /steamapps/ w,
  owner /tmp/miles_image_* m,
  owner @{HOME}*/Steam/ r,
  owner @{HOME}*/Steam/** k,
  owner @{HOME}*/Steam/** r,
  owner @{HOME}*/Steam/** w,
  owner @{HOME}*/Steam/.steam_exec_test.sh mrw,
  owner @{HOME}/ r,
  owner @{HOME}/.cache/mesa_shader_cache/** w,
  owner @{HOME}/.config/autostart/steam.desktop w,
  owner @{HOME}/.config/fish/* r,
  owner @{HOME}/.config/gtk-3.0/* r,
  owner @{HOME}/.config/gtkrc-2.0 r,
  owner @{HOME}/.local/share/Steam/ r,
  owner @{HOME}/.local/share/Steam/* r,
  owner @{HOME}/.local/share/Steam/* w,
  owner @{HOME}/.local/share/Steam/** m,
  owner @{HOME}/.local/share/Steam/** rwk,
  owner @{HOME}/.local/share/Steam/**/ r,
  owner @{HOME}/.local/share/Steam/**/ w,
  owner @{HOME}/.local/share/Steam/*/ r,
  owner @{HOME}/.local/share/Steam/.crash w,
  owner @{HOME}/.local/share/Steam/.writable w,
  owner @{HOME}/.local/share/Steam/appcache/* r,
  owner @{HOME}/.local/share/Steam/appcache/packageinfo.vdf r,
  owner @{HOME}/.local/share/Steam/bin/ r,
  owner @{HOME}/.local/share/Steam/bin/*/ r,
  owner @{HOME}/.local/share/Steam/bin/panorama/** rw,
  owner @{HOME}/.local/share/Steam/bin_steam.sh r,
  owner @{HOME}/.local/share/Steam/config/* r,
  owner @{HOME}/.local/share/Steam/config/* w,
  owner @{HOME}/.local/share/Steam/config/widevine/linux-x64/* rw,
  owner @{HOME}/.local/share/Steam/controller_base/d0ggle.bin r,
  owner @{HOME}/.local/share/Steam/linux32/* r,
  owner @{HOME}/.local/share/Steam/linux64/* r,
  owner @{HOME}/.local/share/Steam/logs/* wk,
  owner @{HOME}/.local/share/Steam/logs/bootstrap_log.txt w,
  owner @{HOME}/.local/share/Steam/package/ r,
  owner @{HOME}/.local/share/Steam/package/* r,
  owner @{HOME}/.local/share/Steam/package/* w,
  owner @{HOME}/.local/share/Steam/package/tmp/ rw,
  owner @{HOME}/.local/share/Steam/package/tmp/** rk,
  owner @{HOME}/.local/share/Steam/package/tmp/** w,
  owner @{HOME}/.local/share/Steam/package/tmp/**/ rw,
  owner @{HOME}/.local/share/Steam/package/tmp/*/ rw,
  owner @{HOME}/.local/share/Steam/public/ r,
  owner @{HOME}/.local/share/Steam/public/* r,
  owner @{HOME}/.local/share/Steam/resource/** r,
  owner @{HOME}/.local/share/Steam/steam/cached/* r,
  owner @{HOME}/.local/share/Steam/steamdeps.txt rw,
  owner @{HOME}/.local/share/Steam/tenfoot/resource/** rw,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/ r,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/* mr,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/crashhandler.so r,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/panorama/* r,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime.checksum r,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime.tar.xz rw,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime.tar.xz.part0 r,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime.tar.xz.part1 r,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime.tmp/ w,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/* r,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/** mr,
  owner @{HOME}/.local/share/Steam/ubuntu12_32/steam-runtime/checksum r,
  owner @{HOME}/.local/share/Steam/ubuntu12_64/ r,
  owner @{HOME}/.local/share/Steam/ubuntu12_64/* r,
  owner @{HOME}/.local/share/Steam/ubuntu12_64/** r,
  owner @{HOME}/.local/share/Steam/ubuntu12_64/** w,
  owner @{HOME}/.local/share/vulkan/implicit_layer.d/* wk,
  owner @{HOME}/.steam/ r,
  owner @{HOME}/.steam/* r,
  owner @{HOME}/.steam/* w,
  owner @{HOME}/.steam/bin w,
  owner @{HOME}/.steam/bin32 w,
  owner @{HOME}/.steam/bin64 w,
  owner @{HOME}/.steam/registry.vdf rw,
  owner @{HOME}/.steam/registry.vdf20190827164541 w,
  owner @{HOME}/.steam/root w,
  owner @{HOME}/.steam/sdk32 w,
  owner @{HOME}/.steam/sdk64 w,
  owner @{HOME}/.steam/starting w,
  owner @{HOME}/.steam/steam w,
  owner @{HOME}/.steam/steam.pid rw,
  owner @{HOME}/.steam/steam.pipe r,
  owner @{HOME}/.steampath w,
  owner @{HOME}/.steampid w,
  owner @{HOME}/Tiedostot/ r,
  owner @{HOME}/Tiedostot/Sek/ r,


  profile /home/smar/.local/share/Steam/.steam_exec_test.sh {
    #include <abstractions/base>
    #include <abstractions/consoles>

    /bin/bash mr,
    owner /home/*/.local/share/Steam/.steam_exec_test.sh r,
    owner /home/*/.steam/steam.pipe r,

  }
}
